name: first workflow
on:
  workflow_dispatch:

jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: firstJob script
        shell: bash
        run: echo Hello World! This is the first job
      - name: checkout
        uses: actions/checkout@v6
      - name: Print to Log
        id: print-to-log
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: ${{ github.actor }}
      - name: time
        run: |
          echo "The time of greeting was at: ${{ steps.print-to-log.outputs.time }}"
  secondjob:
    runs-on: ubuntu-latest
    needs: firstjob
    env:
      JOB_VAR: "This is a job variable"
    steps:
      - name: secondJob script
        shell: bash
        run: |
            echo this is the second job
            echo and this is a multi-line script
      - name: enviroment variables
        env: 
          STEP_VAR: "This is step level variable"
